export default Object.freeze({
  REGISTER: 'Register',
  LOGIN: 'Login',
  PROFILE: 'Profile',
  FORGOT_PASSWORD: 'Forgot_Password',
  CHANGE_PASSWORD: 'Change_Password',
  PAYMENT_INFO: 'Payment_Info',
  HOME: 'Home',
  DASHBOARD: 'Dashboard',
  CATEGORY: 'Category',
  CATEGORY_INDEX: 'CategoryIndex',
  CATEGORY_DETAILS: 'CategoryDetails',
  SETTING: 'Setting',
  SETTING_INDEX: 'SettingIndex',
  FAVORITES: 'Favorites',
  AUDIO: 'Audio',
  WEBVIEW: 'Webview',
  MAIN: 'Main',
  PAYMENT_PORTAL: 'Payment_Portal',
  SUBSCRIPTION_DETAILS: 'SubscriptionDetails',
});
